# Generated by Django 2.1 on 2021-04-11 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro_menu', models.CharField(max_length=20)),
                ('intro_description', models.CharField(max_length=2083)),
                ('intro_link', models.CharField(max_length=255)),
            ],
        ),
    ]
